version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Smart2024
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  usermanagement-api:
    build:
      context: ./usermanagement-api
      dockerfile: Dockerfile
    container_name: usermanagement-api
    environment:
      - ConnectionStrings__PostgresConnection=Host=postgres;Port=5432;Database=usermanagement;Username=awmappauser;Password=Smart2024#
    depends_on:
      - postgres
    ports:
      - "5001:8080"

  workorder-api:
    build:
      context: ./workorder-api
      dockerfile: Dockerfile
    container_name: workorder-api
    environment:
      - ConnectionStrings__PostgresConnection=Host=postgres;Port=5432;Database=workorders;Username=awmappauser;Password=Smart2024#
    depends_on:
      - postgres
    ports:
      - "5002:8080"

  assets-api:
    build:
      context: ./assets-api
      dockerfile: Dockerfile
    container_name: assets-api
    environment:
      - ConnectionStrings__PostgresConnection=Host=postgres;Port=5432;Database=assets;Username=awmappauser;Password=Smart2024#
    depends_on:
      - postgres
    ports:
      - "5003:8080"

volumes:
  postgres_data:
